"""add dimensions column to metrics

Revision ID: 1638d5363473
Revises: 78a96dfb724f
Create Date: 2026-05-17 05:24:09.018780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1638d5363473'
down_revision: Union[str, Sequence[str], None] = '78a96dfb724f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_metrics_dimensions', 'metrics', ['dimensions'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_dimensions', table_name='metrics', postgresql_using='gin')
    op.drop_column('metrics', 'dimensions')
    # ### end Alembic commands ###
