"""make reasoning column nullable in agent_logs

Revision ID: b731a5ecbe51
Revises: 1638d5363473
Create Date: 2026-05-17 07:15:50.884634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b731a5ecbe51'
down_revision: Union[str, Sequence[str], None] = '1638d5363473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
